version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - bash <(curl -s https://codecov.io/bash)
artifacts:
  files:
    - 'target/app.jar'
cache:
  paths:
    - '/root/.m2/**/*'