version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - mv target/app.jar .
artifacts:
  files:
    - 'app.jar'
    - '.ebextensions/**/*'
    - 'Procfile'
cache:
  paths:
    - '/root/.m2/**/*'