version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn -Dspring.profiles.active=test clean package
      - VCS_COMMIT_ID="$CODEBUILD_SOURCE_VERSION"
      - VCS_BRANCH_NAME="$CODEBUILD_SOURCE_VERSION"
      - CI_BUILD_URL=$(echo $CODEBUILD_AGENT_ENV_CODEBUILD_BUILD_URL | sed 's/#/%23/g')
      - CI_BUILD_ID="${CODEBUILD_BUILD_ID}"
      - COV_SCRIPT=/root/.cache/codecov.sh
      - if [ ! -n "$CODEBUILD_SOURCE_VERSION" ]; then mvn sonar:sonar -Dsonar.projectKey=ajurasz_aws-ci-demo -Dsonar.organization=ajurasz-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_CLOUD_TOKEN -Dsonar.junit.reportPaths=target/surefire-reports -Dsonar.jacoco.reportPaths=target/jacoco.exec; fi
artifacts:
  files:
    - 'target/app.jar'
  discard-paths: yes
cache:
  paths:
    - '/root/.cache/codecov.sh'
    - '/root/.m2/**/*'