version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn -Dspring.profiles.active=test clean package
      - VCS_COMMIT_ID="$CODEBUILD_SOURCE_VERSION"
      - VCS_BRANCH_NAME="$CODEBUILD_SOURCE_VERSION"
      - CI_BUILD_URL=$(echo $CODEBUILD_AGENT_ENV_CODEBUILD_BUILD_URL | sed 's/#/%23/g')
      - CI_BUILD_ID="${CODEBUILD_BUILD_ID}"
      - COV_SCRIPT=/root/.cache/codecov.sh
      - if [ ! -f "$COV_SCRIPT" ]; then curl -s https://codecov.io/bash > "$COV_SCRIPT"; fi
      - bash "$COV_SCRIPT" -t $CODECOV_TOKEN
artifacts:
  files:
    - 'target/app.jar'
  discard-paths: yes
cache:
  paths:
    - '/root/.cache/codecov.sh'
    - '/root/.m2/**/*'